stages:
- test

language: node_js
node_js:
- '10'

install:
- script/ci-deps
- script/install-shadow-node --global
- yarn

script:
- script/install
- yarn build

jobs:
  include:
  - stage: test
    os: linux
    dist: trusty
