#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=90
USE_PROCD=1
PROG=/usr/bin/iotjs

start_service() {
    procd_open_instance
    procd_set_param command $PROG /data/hive/lib/flora-server.js
    procd_set_param env NODE_PRIORITIZED_PATH=/usr/lib/node_modules PULSEAUDIO_HOME=/var/run/pulse
    procd_set_param respawn 3600 2 -1
    procd_set_param stdout 1
    procd_set_param stderr 1
    [ -e /data/coredump ] && {
        procd_set_param limits core="unlimited"
    }
    procd_close_instance
}
